import { Institution, User, ResearchProject, Notification } from '@/types';

export const DUMMY_INSTITUTIONS: Institution[] = [
  {
    id: 'inst-001',
    name: 'University of Technology',
    code: 'UOT',
    logo_url: '',
    primary_color: '#0B5ED7',
    secondary_color: '#198754',
    country: 'Kenya',
    type: 'university',
    subscription_status: 'active',
    created_at: '2024-01-15T00:00:00Z',
  },
  {
    id: 'inst-002',
    name: 'Nairobi Business College',
    code: 'NBC',
    logo_url: '',
    primary_color: '#198754',
    secondary_color: '#0B5ED7',
    country: 'Kenya',
    type: 'college',
    subscription_status: 'active',
    created_at: '2024-03-10T00:00:00Z',
  },
  {
    id: 'inst-003',
    name: 'East Africa Research Institute',
    code: 'EARI',
    logo_url: '',
    primary_color: '#0B5ED7',
    secondary_color: '#FFC107',
    country: 'Tanzania',
    type: 'research_org',
    subscription_status: 'trial',
    created_at: '2024-06-01T00:00:00Z',
  },
];

export const DUMMY_USERS: User[] = [
  {
    id: 'user-001',
    institution_id: 'inst-001',
    email: 'alice.njoroge@uot.ac.ke',
    full_name: 'Alice Njoroge',
    role: 'student',
    department: 'Computer Science',
    faculty: 'Science & Technology',
    is_active: true,
    created_at: '2024-02-01T00:00:00Z',
  },
  {
    id: 'user-002',
    institution_id: 'inst-001',
    email: 'dr.kamau@uot.ac.ke',
    full_name: 'Dr. James Kamau',
    role: 'supervisor',
    department: 'Computer Science',
    faculty: 'Science & Technology',
    is_active: true,
    created_at: '2024-01-20T00:00:00Z',
  },
  {
    id: 'user-003',
    institution_id: 'inst-001',
    email: 'prof.wanjiru@uot.ac.ke',
    full_name: 'Prof. Mary Wanjiru',
    role: 'coordinator',
    department: 'Graduate Studies',
    faculty: 'Science & Technology',
    is_active: true,
    created_at: '2024-01-18T00:00:00Z',
  },
  {
    id: 'user-004',
    institution_id: 'inst-001',
    email: 'dr.omondi@uot.ac.ke',
    full_name: 'Dr. Peter Omondi',
    role: 'examiner',
    department: 'Information Technology',
    faculty: 'Science & Technology',
    is_active: true,
    created_at: '2024-01-22T00:00:00Z',
  },
  {
    id: 'user-005',
    institution_id: 'inst-001',
    email: 'admin@uot.ac.ke',
    full_name: 'Sarah Mutua',
    role: 'institution_admin',
    department: 'Administration',
    is_active: true,
    created_at: '2024-01-15T00:00:00Z',
  },
  {
    id: 'user-006',
    institution_id: 'inst-001',
    email: 'brian.otieno@uot.ac.ke',
    full_name: 'Brian Otieno',
    role: 'student',
    department: 'Business Administration',
    faculty: 'Business',
    is_active: true,
    created_at: '2024-02-05T00:00:00Z',
  },
  {
    id: 'user-007',
    institution_id: 'inst-001',
    email: 'dr.chebet@uot.ac.ke',
    full_name: 'Dr. Rose Chebet',
    role: 'peer_reviewer',
    department: 'Research & Innovation',
    is_active: true,
    created_at: '2024-01-25T00:00:00Z',
  },
];

export const DUMMY_PROJECTS: ResearchProject[] = [
  {
    id: 'proj-001',
    institution_id: 'inst-001',
    student_id: 'user-001',
    title: 'Machine Learning Approaches for Early Disease Detection in Resource-Limited Settings',
    abstract: 'This research investigates the application of machine learning algorithms for early detection of infectious diseases in environments with limited computational resources and medical infrastructure.',
    field_of_study: 'Computer Science',
    program: 'PhD Computer Science',
    project_type: 'phd_dissertation',
    selected_duration_months: 24,
    project_start_date: '2024-02-01',
    project_deadline: '2026-02-01',
    project_status: 'active',
    extension_count: 0,
    supervisor_id: 'user-002',
    current_stage: 'proposal_development',
    status: 'in_progress',
    progress_percentage: 35,
    start_date: '2024-02-01',
    expected_completion: '2027-01-31',
    created_at: '2024-02-01T00:00:00Z',
    updated_at: '2024-11-15T00:00:00Z',
  },
  {
    id: 'proj-002',
    institution_id: 'inst-001',
    student_id: 'user-006',
    title: 'Impact of Mobile Banking on Financial Inclusion in Rural Communities',
    abstract: 'An empirical study examining how mobile banking technologies have transformed financial access and economic participation in rural sub-Saharan African communities.',
    field_of_study: 'Business Administration',
    program: 'Masters Business Administration',
    project_type: 'masters_thesis',
    selected_duration_months: 8,
    project_start_date: '2024-09-01',
    project_deadline: '2025-05-01',
    project_status: 'active',
    extension_count: 0,
    supervisor_id: 'user-002',
    current_stage: 'concept_paper',
    status: 'submitted',
    progress_percentage: 15,
    start_date: '2024-09-01',
    expected_completion: '2026-08-31',
    created_at: '2024-09-01T00:00:00Z',
    updated_at: '2024-10-20T00:00:00Z',
  },
  {
    id: 'proj-003',
    institution_id: 'inst-001',
    student_id: 'user-001',
    title: 'Blockchain-Based Academic Credential Verification System',
    abstract: 'Designing and implementing a decentralized system for secure academic credential issuance and verification using blockchain technology.',
    field_of_study: 'Information Technology',
    program: 'Masters IT',
    project_type: 'masters_thesis',
    selected_duration_months: 6,
    project_start_date: '2023-02-01',
    project_deadline: '2023-08-01',
    project_status: 'completed',
    extension_count: 0,
    supervisor_id: 'user-003',
    current_stage: 'final_defense',
    status: 'approved',
    progress_percentage: 88,
    start_date: '2023-02-01',
    expected_completion: '2025-01-31',
    created_at: '2023-02-01T00:00:00Z',
    updated_at: '2024-11-01T00:00:00Z',
  },
  {
    id: 'proj-004',
    institution_id: 'inst-001',
    student_id: 'user-006',
    title: 'Sustainable Agricultural Practices and Climate Resilience',
    abstract: 'Evaluating the adoption of sustainable farming practices and their contribution to climate resilience in small-scale farming communities.',
    field_of_study: 'Environmental Science',
    program: 'PhD Environmental Studies',
    project_type: 'phd_dissertation',
    selected_duration_months: 24,
    project_start_date: '2022-09-01',
    project_deadline: '2024-09-01',
    project_status: 'expired',
    extension_count: 1,
    supervisor_id: 'user-002',
    current_stage: 'peer_review',
    status: 'under_review',
    progress_percentage: 92,
    start_date: '2022-09-01',
    expected_completion: '2025-06-30',
    created_at: '2022-09-01T00:00:00Z',
    updated_at: '2024-11-10T00:00:00Z',
  },
  {
    id: 'proj-005',
    institution_id: 'inst-001',
    student_id: 'user-001',
    title: 'Natural Language Processing for Swahili Text Summarization',
    abstract: 'Development of NLP models specifically trained for automatic summarization of Swahili language texts for academic and media applications.',
    field_of_study: 'Computer Science',
    program: 'Masters Computer Science',
    project_type: 'undergraduate',
    selected_duration_months: 6,
    project_start_date: '2024-01-10',
    project_deadline: '2024-07-10',
    project_status: 'active',
    extension_count: 0,
    supervisor_id: 'user-002',
    current_stage: 'corrections',
    status: 'revision_required',
    progress_percentage: 75,
    start_date: '2023-09-01',
    expected_completion: '2025-08-31',
    created_at: '2023-09-01T00:00:00Z',
    updated_at: '2024-10-30T00:00:00Z',
  },
];

export const DUMMY_NOTIFICATIONS: Notification[] = [
  {
    id: 'notif-001',
    user_id: 'user-001',
    title: 'Concept Paper Approved',
    message: 'Your concept paper for "Machine Learning for Disease Detection" has been approved. Please proceed to proposal development.',
    type: 'success',
    is_read: false,
    action_url: '/dashboard/student/projects/proj-001',
    created_at: '2024-11-15T09:30:00Z',
  },
  {
    id: 'notif-002',
    user_id: 'user-001',
    title: 'Supervisor Feedback',
    message: 'Dr. James Kamau has left feedback on your proposal draft. Please review and make corrections.',
    type: 'info',
    is_read: false,
    action_url: '/dashboard/student/projects/proj-001',
    created_at: '2024-11-14T14:15:00Z',
  },
  {
    id: 'notif-003',
    user_id: 'user-001',
    title: 'Deadline Reminder',
    message: 'Your proposal submission deadline is in 7 days (Nov 22, 2024).',
    type: 'warning',
    is_read: true,
    action_url: '/dashboard/student/projects/proj-001',
    created_at: '2024-11-13T08:00:00Z',
  },
  {
    id: 'notif-004',
    user_id: 'user-002',
    title: 'New Supervision Request',
    message: 'Brian Otieno has requested you as supervisor for "Impact of Mobile Banking on Financial Inclusion".',
    type: 'info',
    is_read: false,
    action_url: '/dashboard/supervisor/requests',
    created_at: '2024-11-15T11:00:00Z',
  },
  {
    id: 'notif-005',
    user_id: 'user-003',
    title: 'Defense Scheduled',
    message: 'Final defense for "Blockchain-Based Academic Credential Verification" is scheduled for Dec 10, 2024.',
    type: 'info',
    is_read: false,
    action_url: '/dashboard/coordinator/defenses',
    created_at: '2024-11-12T16:45:00Z',
  },
];

export const DUMMY_ACTIVITIES = [
  {
    id: 'act-001',
    user: 'Alice Njoroge',
    action: 'submitted concept paper',
    project: 'Machine Learning for Disease Detection',
    time: '2 hours ago',
    type: 'submission',
  },
  {
    id: 'act-002',
    user: 'Dr. James Kamau',
    action: 'approved proposal',
    project: 'Blockchain Credential Verification',
    time: '5 hours ago',
    type: 'approval',
  },
  {
    id: 'act-003',
    user: 'Brian Otieno',
    action: 'uploaded research report',
    project: 'Mobile Banking & Financial Inclusion',
    time: '1 day ago',
    type: 'upload',
  },
  {
    id: 'act-004',
    user: 'Prof. Mary Wanjiru',
    action: 'scheduled defense panel',
    project: 'Blockchain Credential Verification',
    time: '2 days ago',
    type: 'schedule',
  },
  {
    id: 'act-005',
    user: 'Dr. Rose Chebet',
    action: 'submitted peer review',
    project: 'Sustainable Agricultural Practices',
    time: '3 days ago',
    type: 'review',
  },
];
